name: Build TWRP for Samsung A10s

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup System
      run: |
        sudo apt-get update
        sudo apt-get install -y bc build-essential jsoncpp libccid libgconf-2-4 libtinfo5 libgfortran5 libgl1 libtinfo-dev libxml2-utils zip python2

    - name: Download Source and Build
      run: |
        mkdir twrp && cd twrp
        # Завантажуємо вихідний код TWRP (гілка 9.0)
        repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-9.0
        repo sync -j$(nproc --all)
        
        # Клонуємо твоє дерево пристрою у правильну папку
        git clone https://github.com/${{ github.repository }} device/samsung/a10s
        
        # Запускаємо компіляцію
        source build/envsetup.sh
        lunch omni_a10s-eng
        make recoveryimage -j$(nproc --all)

    - name: Upload Finished File
      uses: actions/upload-artifact@v3
      with:
        name: TWRP-Samsung-A10s
        path: twrp/out/target/product/a10s/recovery.img
